apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-volume
provisioner: efs.csi.aws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-volume
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-07c79f55f79ee1bb4

#---

#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: mongo-pvc
#spec:
#  accessModes:
#    - ReadWriteMany
#  storageClassName: efs-sc
#  resources:
#    requests:
#      storage: 20Gi